const actionType = {
    CHANGE_NATION: "CHANGE_NATION",
    RESET_ALL_POINTS: "RESET_ALL_POINTS",

    CHANGE_FIRE: "CHANGE_FIRE",
    CHANGE_AIR: "CHANGE_AIR",
    CHANGE_WATER: "CHANGE_WATER",
    CHANGE_EARTH: "CHANGE_EARTH",
    CHANGE_ASTRAL: "CHANGE_ASTRAL",
    CHANGE_DEATH: "CHANGE_DEATH",
    CHANGE_NATURE: "CHANGE_NATURE",
    CHANGE_BLOOD: "CHANGE_BLOOD",
    RESET_MAGIC_POINTS: "RESET_MAGIC_POINTS",

    CHANGE_DOMINION: "CHANGE_DOMINION",
    CHANGE_ORDER: "CHANGE_ORDER",
    INCREASE_ORDER: "INCREASE_ORDER",
    DECREASE_ORDER: "DECREASE_ORDER",
    CHANGE_PRODUCTIVITY: "CHANGE_PRODUCTIVITY",
    INCREASE_PRODUCTIVITY: "INCREASE_PRODUCTIVITY",
    DECREASE_PRODUCTIVITY: "DECREASE_PRODUCTIVITY",
    CHANGE_HEAT: "CHANGE_HEAT",
    INCREASE_HEAT: "INCREASE_HEAT",
    DECREASE_HEAT: "DECREASE_HEAT",
    CHANGE_GROWTH: "CHANGE_GROWTH",
    INCREASE_GROWTH: "INCREASE_GROWTH",
    DECREASE_GROWTH: "DECREASE_GROWTH",
    CHANGE_FORTUNE: "CHANGE_FORTUNE",
    INCREASE_FORTUNE: "INCREASE_FORTUNE",
    DECREASE_FORTUNE: "DECREASE_FORTUNE",
    CHANGE_MAGIC: "CHANGE_MAGIC",
    INCREASE_MAGIC: "INCREASE_MAGIC",
    DECREASE_MAGIC: "DECREASE_MAGIC",
    RESET_SCALES_POINTS: "RESET_SCALES_POINTS",

    CHANGE_IMPRISONMENT: "CHANGE_IMPRISONMENT",

    TOGGLE_IMMOBILES: "TOGGLE_IMMOBILES",
    TOGGLE_TITANS: "TOGGLE_TITANS",
    TOGGLE_MONSTERS: "TOGGLE_MONSTERS",
    TOGGLE_HUMANOIDS: "TOGGLE_HUMANOIDS",

    SHOW_BLESS_LIST: "SHOW_BLESS_LIST",
    CLOSE_BLESS_LIST: "CLOSE_BLESS_LIST",
};

export default actionType;
