const actionType = {
    CHANGE_NATION: "CHANGE_NATION",
    RESET_ALL_POINTS: "RESET_ALL_POINTS",

    CHANGE_FIRE: "CHANGE_FIRE",
    CHANGE_AIR: "CHANGE_AIR",
    CHANGE_WATER: "CHANGE_WATER",
    CHANGE_EARTH: "CHANGE_EARTH",
    CHANGE_ASTRAL: "CHANGE_ASTRAL",
    CHANGE_DEATH: "CHANGE_DEATH",
    CHANGE_NATURE: "CHANGE_NATURE",
    CHANGE_BLOOD: "CHANGE_BLOOD",
    RESET_MAGIC_POINTS: "RESET_MAGIC_POINTS",

    CHANGE_DOMINION: "CHANGE_DOMINION",
    CHANGE_ORDER: "CHANGE_ORDER",
    CHANGE_PRODUCTIVITY: "CHANGE_PRODUCTIVITY",
    CHANGE_HEAT: "CHANGE_HEAT",
    CHANGE_GROWTH: "CHANGE_GROWTH",
    CHANGE_FORTUNE: "CHANGE_FORTUNE",
    CHANGE_MAGIC: "CHANGE_MAGIC",
    RESET_SCALES_POINTS: "RESET_SCALES_POINTS",

    CHANGE_IMPRISONMENT: "CHANGE_IMPRISONMENT",

    SHOW_BLESS_LIST: "SHOW_BLESS_LIST",
    CLOSE_BLESS_LIST: "CLOSE_BLESS_LIST",
};

export default actionType;
