export const blessEffects = [
  {id: 1   , f: 1, scales:{}, name: "Superior Morale",},
  {id: 2   , f: 2, scales:{}, name: "Minor Fire Resistance",},
  {id: 3   , f: 3, scales:{}, name: "Major Fire Resistance",},
  {id: 4   , f: 1, d: 1, scales:{}, name: "Wasteland Survival",},
  {id: 5   , f: 3, scales:{}, name: "Attack Skill",},
  {id: 6   , f: 4, scales:{}, name: "Inspirational Presence",},
  {id: 7   , f: 5, scales:{}, name: "Death Explosion", incarnate: true},
  {id: 8   , f: 5, scales:{}, name: "Heat Aura", incarnate: true},
  {id: 9   , f: 6, scales:{}, name: "Fire Shield", incarnate: true,},
  {id: 10  , f: 6, scales:{}, name: "Flaming Weapons", incarnate: true,},
  {id: 11  , f: 7, scales:{}, name: "Awe", incarnate: true,},
  {id: 12  , a: 1, scales:{}, name: "Minor Shock Resistance",},
  {id: 13  , a: 1, scales:{}, name: "Precision",},
  {id: 14  , a: 2, scales:{}, name: "Farshot",},
  {id: 15  , a: 2, scales:{}, name: "Swiftness",},
  {id: 16  , a: 3, scales:{}, name: "Major Shock Resistance",},
  {id: 17  , a: 4, scales:{}, name: "Charged Bodies",},
  {id: 18  , a: 5, scales:{}, name: "Wind Walker", incarnate: true,},
  {id: 19  , a: 6, scales:{}, name: "Air Shield", incarnate: true,},
  {id: 20  , a: 7, scales:{}, name: "Thunder Weapons", incarnate: true,},
  {id: 21  , w: 1, scales:{}, name: "Minor Cold Resistance",},
  {id: 22  , w: 1, scales: {heat: -1}, name: "Winter’s Gift",},
  {id: 23  , w: 1, n: 1, scales:{}, name: "Swamp Survival",},
  {id: 24  , w: 2, scales:{}, name: "Water Walking",},
  {id: 25  , w: 3, scales:{}, name: "Major Cold Resistance",},
  {id: 26  , w: 3, scales:{}, name: "Defense Skill",},
  {id: 27  , w: 5, scales: {heat: -1}, name: "Frost Weapons", incarnate: true,},
  {id: 28  , w: 5, scales:{}, name: "Chill Aura", incarnate: true,},
  {id: 29  , w: 7, scales:{}, name: "Water Breathing", incarnate: true,},
  {id: 30  , w: 10, scales:{}, name: "Quickness", incarnate: true,},
  {id: 31  , e: 1, scales:{}, name: "Mountain Survival",},
  {id: 32  , e: 2, scales:{}, name: "Reinvigoration",},
  {id: 33  , e: 2, scales:{}, name: "Reconstruction",},
  {id: 34  , e: 3, scales:{}, name: "Strength of the Earth",},
  {id: 35  , e: 4, scales:{}, name: "Unbreakable",},
  {id: 36  , e: 5, scales:{}, name: "Fire & Shock Resistance", incarnate: true,},
  {id: 37  , e: 5, n: 3, scales:{}, name: "Larger", incarnate: true,},
  {id: 38  , e: 6, scales:{}, name: "Hard Skin", incarnate: true,},
  {id: 39  , e: 7, scales:{}, name: "Fortitude", incarnate: true,},
  {id: 40  , s: 1, scales:{}, name: "Minor Magic Resistance",},
  {id: 41  , s: 1, scales:{}, name: "Arcane Command",},
  {id: 42  , s: 1, d: 1, scales:{}, name: "Spirit Sight",},
  {id: 43  , s: 2, scales:{}, name: "Magic Weapons",},
  {id: 44  , s: 3, scales:{}, name: "Major Magic Resistance",},
  {id: 45  , s: 3, f: 1, scales:{}, name: "Solar Weapons",},
  {id: 46  , s: 4, scales:{}, name: "Far Caster",},
  {id: 47  , s: 4, scales:{}, name: "Arcane Finesse",},
  {id: 48  , s: 6, scales:{}, name: "Twist Fate", incarnate: true,},
  {id: 49  , s: 7, scales: {fortune: -1},name: "Fateweaving", incarnate: true,},
  {id: 50  , s: 8, scales: {fortune: 1},name: "Luck", incarnate: true,},
  {id: 51  , s: 10, scales: {magic: 1},name: "Etherealness", incarnate: true,},
  {id: 52  , d: 1, scales:{}, name: "Undying",},
  {id: 53  , d: 1, scales:{}, name: "Undead Command",},
  {id: 54  , d: 2, scales: {growth: -2}, name: "Half Dead",},
  {id: 55  , d: 4, scales:{}, name: "Withering Weapons",},
  {id: 56  , d: 5, scales:{}, name: "Stygian Flesh", incarnate: true,},
  {id: 57  , d: 7, scales:{}, name: "Reanimators", incarnate: true,},
  {id: 58  , d: 7, scales:{}, name: "Reforming Flesh", incarnate: true,},
  {id: 59  , d: 8, scales:{}, name: "Death Weapons", incarnate: true,},
  {id: 60  , d: 10, scales:{}, name: "Fear", incarnate: true,},
  {id: 61  , n: 1, scales:{}, name: "Resilient",},
  {id: 62  , n: 1, scales:{}, name: "Low Light Vision",},
  {id: 63  , n: 1, scales:{}, name: "Minor Poison Resistance",},
  {id: 64  , n: 2, scales:{}, name: "Major Poison Resistance",},
  {id: 65  , n: 2, scales:{}, name: "Forest Survival",},
  {id: 66  , n: 3, scales: {magic: 1}, name: "Unaging",},
  {id: 67  , n: 4, scales: {growth: -1}, name: "Poison Weapons",},
  {id: 68  , n: 5, scales:{}, name: "Recuperation", incarnate: true,},
  {id: 69  , n: 5, scales:{}, name: "Berserker", incarnate: true,},
  {id: 70  , n: 6, scales:{}, name: "Barkskin", incarnate: true,},
  {id: 71  , n: 7, scales:{}, name: "Regeneration", incarnate: true,},
  {id: 72  , b: 1, scales:{}, name: "Strong Vitae",},
  {id: 73  , b: 3, scales:{}, name: "Strength of the Flesh",},
  {id: 74  , b: 4, scales:{}, name: "Blood Surge",},
  {id: 75  , b: 5, scales:{}, name: "Blood Bond", incarnate: true,},
  {id: 76  , b: 6, scales:{}, name: "Unholy Weapons", incarnate: true,},
  {id: 77  , b: 8, scales:{}, name: "Blood Vengeance", incarnate: true,},
];
